strike_app/strike/models.py
from strike_app import db

class Striker(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(40), nullable=False)
    strike = db.Column(db.String(1), nullable=False)
    age = db.Column(db.Integer)

strike_app/strike/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, RadioField, IntegerField, validators

class StrikeForm(FlaskForm):
    name = StringField("Wat is je naam?", validators=[validators.DataRequired()])
    strike = RadioField("Ga je staken?", choices=[("y", "Ja"), ("n", "Nee")])
    age = IntegerField("Wat is je leeftijd?", validators=[validators.NumberRange(18)])
    submit = SubmitField("Verzend")

strike_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

### App configuration

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///strike.sqlite"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = "bvjchsygvduycgsyugc"

### ORM

db = SQLAlchemy()
db.init_app(app)

migrate = Migrate(app, db)

### Login manager

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'

from strike_app.auth.models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

### Register blueprints

from strike_app.strike.views import strike_blueprint
app.register_blueprint(strike_blueprint, url_prefix="/staking")

from strike_app.auth.views import auth_blueprint
app.register_blueprint(auth_blueprint, url_prefix='/auth')

strike_app/strike/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, get_flashed_messages
from strike_app import db
from strike_app.strike.models import Striker
from strike_app.strike.forms import StrikeForm
from flask_login import login_required, current_user

strike_blueprint = Blueprint('staking', __name__, template_folder='templates')

### Routes

@strike_blueprint.route("/bedankt", methods=["GET"])
def thanks():
    return render_template("bedankt.html")

@strike_blueprint.route("/", methods=["GET", "POST"])
def index():
    session['_flashes'] = []
    my_form = StrikeForm()

    if request.method == "POST":
        if my_form.validate_on_submit():
            flash("Het formulier is succesvol gePOST")

            session["name"] = my_form.name.data
            session["strike"] = my_form.strike.data
            session["age"] = my_form.age.data
            flash("De gegevens zijn in de sessie opgeslagen")

            new_striker = Striker(name=my_form.name.data, strike=my_form.strike.data, age=my_form.age.data)
            db.session.add(new_striker)
            db.session.commit()
            flash("De gegevens zijn in de database opgeslagen")

            return redirect(url_for("staking.thanks"))
        else:
            flash("Het formulier is niet goed ingevuld")
            
    return render_template("strike.html", form=my_form)

@strike_blueprint.route("/stakers")
@login_required
def strikers():
    rows = Striker.query.all()
    return render_template("strikers.html", rows=rows, user=current_user.username)

strike_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='my.css')}}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Staak-app</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{{url_for('index')}}">Home</a>
              <a class="nav-link" href="{{url_for('staking.index')}}">Aanmelden</a>
              <a class="nav-link" href="{{url_for('staking.strikers')}}">Overzicht</a>
              {% if current_user.is_authenticated %}
              <a class="nav-link" href="{{url_for('auth.logout')}}">Uitloggen</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

strike_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Staak-app
{% endblock %}

{% block content %}
<h1>Welkom bij de staak-app!</h1>
<p>
    <a href="{{url_for('staking.index')}}">Meld je aan</a>
</p>
<p>
    <a href="{{url_for('staking.strikers')}}">Bekijk alle aanmeldingen (alleen voor admin)</a>
</p>
{% endblock %}